#! /bin/sh

prefix=`type gnatcov 2> /dev/null | cut -d' ' -f3 | sed 's%/bin.*$%%'`

clear
printf "    This is the installation script for the dynamic HTML output
    extension for AdaCore's GNATcoverage tool.

    Note that you need GNATcoverage to be already installed in order to
    install this extension.

    To install this package, you need to specify a base directory.
    All the files will be installed in subdirectories that are created
    under this directory.

    Important Note: You should not use ~ or ~username wildcards when
    specifying this directory name.

    In which directory do you want to install this extension?
    [$prefix]: "

read pref

if [ "$pref" != "" ]; then
    prefix=$pref
fi

printf "
    The install directory will be: $prefix
    Do you want to proceed with the installation now? [y|n]: "

read confirm

case $confirm in
    [yY])
        echo "

    Installing package..."

        mkdir -p $prefix
        (cd build/install && tar cf - lib) | (cd $prefix && tar xf -)

        echo "    Installation completed.

    To use this extension, users shall use the --annotate=dhtml switch.
    Thank you for installing this GNATcoverage extension!"
        ;;

    *)
        echo "

    Installation aborted."; exit 1
        ;;
esac
