# Build mode; Possible values: Debug, Production; Default to Debug
BUILD_TYPE := Debug

# Find the top level directory.
ME  := $(word $(words $(MAKEFILE_LIST)), $(MAKEFILE_LIST))
TOP := $(shell cd $(dir $(ME)) && pwd)

VERSION := $(shell cd $(TOP) && cat version.txt)

# Utilities
RM := rm -f
CP := cp -p

RMDIR := rm -rf
MKDIR := mkdir -p

# Build directory where the result of the compilation will be generated.
BUILD := $(TOP)/build

# Bundle directory where to install the XCOV standalone webapp.
BUNDLE := $(BUILD)/install/lib/gnatcoverage

# Thirdparty directory where all dependencies should be installed (see
# $(THIRDPARTIES)/thirdparties.py script).
THIRDPARTIES := $(TOP)/thirdparties

# Directory where all the thirdparties are installed.
TOOLS_DIR := $(THIRDPARTIES)/tooling

# Top-level directory for both Javascript and LESS sources.
SOURCE_DIR := $(TOP)/src

# Top-level directory for the Google Closure Library installation.
CLOSURE_DIR := $(TOOLS_DIR)/closure

# List of javascript source files.
JS_SOURCES := $(shell find $(SOURCE_DIR)/js -name '*.js')

# List of LESS source files.
LESS_SOURCES := $(wildcard $(SOURCE_DIR)/less/*.less)

# Main LESS file, importing all the others. Input for the LESS compiler.
LESS_SOURCE_MAIN := $(SOURCE_DIR)/less/xcov.less

# Javascript compiled file.
JS_TARGET := gnatcov-dhtml.min.js
JS_TARGET_VERSION := gnatcov-dhtml-$(VERSION).min.js

# CSS compiled file.
CSS_TARGET := gnatcov-dhtml.min.css
CSS_TARGET_VERSION := gnatcov-dhtml-$(VERSION).min.css

# Dependency file to have the webapp working in non-compiled mode.
JS_DEPS_TARGET := gnatcov-dhtml-deps.js

# Google Closure build script.
JS_COMPILER := python $(CLOSURE_DIR)/closure/bin/build/closurebuilder.py

# Compiler Java JAR file to provide to the closure build script.
JS_COMPILER_JAR := $(TOOLS_DIR)/bin/compiler.jar

# Parameterization for DEBUG / PRODUCTION builds
JS_COMPILER_DEBUG_OPTIONS := "--compiler_flags=--debug"

ifeq ($(BUILD_TYPE),Production)
  JS_COMPILER_DEBUG_OPTIONS := \
	"--compiler_flags=--define=xcov.DEBUG=false"
endif

# Options to provide to the closure build script.
JS_COMPILER_OPTIONS := \
	"--root=$(SOURCE_DIR)/js" \
	"--root=$(CLOSURE_DIR)" \
	"--namespace=xcov" \
	"--output_mode=compiled" \
	"--compiler_flags=--compilation_level=ADVANCED_OPTIMIZATIONS" \
	"--compiler_flags=--generate_exports" \
	"--compiler_flags=--process_closure_primitives" \
	"--compiler_flags=--jscomp_error=accessControls" \
	"--compiler_flags=--jscomp_error=ambiguousFunctionDecl" \
	"--compiler_flags=--jscomp_error=checkRegExp" \
	"--compiler_flags=--jscomp_error=checkTypes" \
	"--compiler_flags=--jscomp_error=checkVars" \
	"--compiler_flags=--jscomp_error=const" \
	"--compiler_flags=--jscomp_error=constantProperty" \
	"--compiler_flags=--jscomp_error=deprecated" \
	"--compiler_flags=--jscomp_error=duplicateMessage" \
	"--compiler_flags=--jscomp_error=es5Strict" \
	"--compiler_flags=--jscomp_error=externsValidation" \
	"--compiler_flags=--jscomp_error=fileoverviewTags" \
	"--compiler_flags=--jscomp_error=globalThis" \
	"--compiler_flags=--jscomp_error=internetExplorerChecks" \
	"--compiler_flags=--jscomp_error=invalidCasts" \
	"--compiler_flags=--jscomp_error=misplacedTypeAnnotation" \
	"--compiler_flags=--jscomp_error=missingProperties" \
	"--compiler_flags=--jscomp_error=nonStandardJsDocs" \
	"--compiler_flags=--jscomp_error=suspiciousCode" \
	"--compiler_flags=--jscomp_error=strictModuleDepCheck" \
	"--compiler_flags=--jscomp_error=typeInvalidation" \
	"--compiler_flags=--jscomp_error=undefinedNames" \
	"--compiler_flags=--jscomp_error=undefinedVars" \
	"--compiler_flags=--jscomp_error=unknownDefines" \
	"--compiler_flags=--jscomp_error=uselessCode" \
	"--compiler_flags=--jscomp_error=visibility" \
	"--compiler_flags=--warning_level=VERBOSE" \
	"--compiler_jar=$(JS_COMPILER_JAR)" $(JS_COMPILER_DEBUG_OPTIONS)

# Javascript linter for static syntax checking.
JS_LINTER := PATH="$(THIRDPARTIES)/python/bin:$(PATH)" gjslint

# Options to provide to the Javascript linter.
JS_LINTER_OPTIONS := --strict -r

# Dependency file generator needed for non-compiled mode.
JS_DEPS_GENERATOR := python $(CLOSURE_DIR)/closure/bin/build/depswriter.py

# Options to provide to the Google Closure dependency file generator.
JS_DEPS_GENERATOR_OPTIONS := \
	"--root_with_prefix=$(SOURCE_DIR)/js ../../../../../src/js" \
	"--root=$(CLOSURE_DIR)/closure/goog"

# LESS Compiler. Executed with NodeJS.
LESS_COMPILER := PATH="$(TOOLS_DIR)/bin:$(PATH)" lessc

# Options to provide to the LESS compiler.
LESS_COMPILER_OPTIONS := -sm=on -su=on --compress
