/**
 * @fileoverview Provides an internal holder of a trace object.
 */


goog.provide('xcov.TraceFile');

goog.require('goog.Disposable');
goog.require('goog.debug.Logger');
goog.require('goog.string.path');


/******************
 * xcov.TraceFile *
 ******************/



/**
 * A trace object. It holds information about the trace file generated but the
 * coverage tool.
 *
 * @param {string} filename The path (relative or absolute) to the trace file
 *    generated by the coverage tool.
 * @param {string} program The path (relative or absolute) to the executable
 *    file that was analysed by the coverage tool to produce the traces.
 * @param {Date} date A date object corresponding to the generation of the trace
 *    file (its creation).
 * @param {string=} opt_tag Optional tag provided by the user before generation.
 * @constructor
 * @extends {goog.Disposable}
 */
xcov.TraceFile = function(filename, program, date, opt_tag) {
  goog.base(this);

  /**
   * @type {goog.debug.Logger} An custom instance of the logger for this class.
   * @const
   * @private
   */
  this.logger_ = goog.debug.Logger.getLogger('xcov.TraceFile');

  /**
   * @type {string}
   * @const
   * @private
   */
  this.filename_ = filename;

  /**
   * @type {string}
   * @const
   * @private
   */
  this.program_ = program;

  /**
   * @type {Date}
   * @const
   * @private
   */
  this.date_ = date;

  /**
   * @type {?string}
   * @const
   * @private
   */
  this.tag_ = opt_tag || null;
};
goog.inherits(xcov.TraceFile, goog.Disposable);


/******************************
 * xcov.TraceFile.getFilename *
 ******************************/


/**
 * @return {string} The path to the trace file.
 */
xcov.TraceFile.prototype.getFilename = function() {
  return goog.string.path.normalizePath(this.filename_);
};


/*****************************
 * xcov.TraceFile.getProgram *
 *****************************/


/**
 * @return {string} The path to the executable used to produce this trace.
 */
xcov.TraceFile.prototype.getProgram = function() {
  return goog.string.path.normalizePath(this.program_);
};


/**********************************
 * xcov.TraceFile.getFormatedDate *
 **********************************/


/**
 * @return {string} The date at which the trace file has been generated, as a
 *    string.
 */
xcov.TraceFile.prototype.getFormatedDate = function() {
  return this.date_.toString();
};


/*************************
 * xcov.TraceFile.getTag *
 *************************/


/**
 * @return {string} A string representation of the tag.
 */
xcov.TraceFile.prototype.getTag = function() {
  return this.tag_ || '';
};
