/**
 * @fileoverview Provides an internal holder of a trace object.
 */


goog.provide('xcov.Trace');

goog.require('goog.Disposable');
goog.require('goog.debug.Logger');


/**************
 * xcov.Trace *
 **************/



/**
 * A trace object. It holds information about the trace file generated but the
 * coverage tool.
 *
 * @param {string} filename The path (relative or absolute) to the trace file
 *    generated by the coverage tool.
 * @param {string} program The path (relative or absolute) to the executable
 *    file that was analysed by the coverage tool to produce the traces.
 * @param {Date} date A date object corresponding to the generation of the trace
 *    file (its creation).
 * @param {Array.<string>=} opt_tags Optional list of tags attached to the trace
 *    file.
 * @constructor
 * @extends {goog.Disposable}
 */
xcov.Trace = function(filename, program, date, opt_tags) {
  goog.base(this);

  /**
   * @type {goog.debug.Logger} An custom instance of the logger for this class.
   * @private
   */
  this.logger_ = goog.debug.Logger.getLogger('xcov.Trace');

  /** @type {string} */ this.filename = filename;
  /** @type {string} */ this.program = program;
  /** @type {Date} */ this.date = date;

  /**
   * @type {?Array.<string>}
   * @private
   */
  this.tags_ = opt_tags || null;
};
goog.inherits(xcov.Trace, goog.Disposable);
